### ISSUE TITLE
Maybe add singlecoil support?

### ISSUE THREAD

**Issue by YuyangXueEd** [ad12/meddlr#47]
Hello, I am new to MRI reconstruction and plan to learn to use fastMRI with singlecoil dataset and using meddlr to reproduce the VORTEX work. I just read the "VORTEX" paper and I think it was a great work. However, I go through the code and found most functions, such as `meddlr.utils.transforms` or `datasets/format_fastmri.py` is mainly used for multicoil data. Could you please consider adding singlecoil support?

Lookingforward to your reply. Thank you very much!

**Comment by ad12** [comment]
Hi @YuyangXueEd, thanks for your interest in VORTEX and meddlr! We are looking to add support for single coil data, but do not have a set timeline for when that would be available.

In the interim, you should be able to use all functionality in meddlr by passing a dummy `maps` argument, which corresponds to sensitivity maps to each coil. Because there is only one coil, the sensitivity maps would be the 1-tensor (where all entries of the matrix are 1).

The maps tensor should be a complex-valued tensor of shape [batch, height, width, # coils, # maps], which in this case would be [batch, height, width, 1, 1].

**Comment by ad12** [comment]
I am closing this comment for now. let me know if you run into any issues
